name: Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-include-markdown-plugin

      - name: Sync Javadoc to docs/api
        run: |
          mkdir -p docs/api
          rsync -rtc --delete jot-docs/ docs/api/

      - name: Ensure homepage includes README
        run: |
          mkdir -p docs
          if [ ! -s docs/index.md ]; then
            printf '%s\n' '--8<-- "README.md"' > docs/index.md
          fi

      - name: Build MkDocs
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: false
